modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "obsidianui"
version = "${version}"
displayName = "ObsidianUI"
displayURL = "https://github.com/ThinkingStudios/ObsidianUI"
credits="LambdAurora"
authors="TexTrue, ThinkingStudio"
description='''
SpruceUI unofficial architectury port.

Just a GUI library.
'''
logoFile = "icon.png"

[[mixins]]
config = "obsidianui.neoforge.mixins.json"

[[dependencies.obsidianui]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obsidianui]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"
